<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<LangVersion>latestMajor</LangVersion>
		<OutputType>WinExe</OutputType>

		<!-- SDK-Style Project Properties -->
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<ImplicitUsings>enable</ImplicitUsings>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<!-- Nuget Packages -->
	<!-- Nuget Packages -->
	<ItemGroup>
		<PackageReference Include="Autodesk.Authentication"  Version="2.0.1" />
		
		<!--<PackageReference Include="Microsoft.AspNetCore.Connections.Abstractions" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Connections.Client" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Connections.Common" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" Version="8.0.19" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Features" Version="8.0.19" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
		<PackageReference Include="System.ComponentModel.Composition" Version="9.0.8" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
		<PackageReference Include="System.IO.Pipelines" Version="8.0.0" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
		<PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.6" />
		<PackageReference Include="System.Threading.Channels" Version="8.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" Version="2.0.0" />-->
	</ItemGroup>
</Project>