<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>

		<!-- SDK-Style Project Properties -->
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<!-- Nuget Packages -->
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>
</Project>